config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :users
  resources :jokes, only: [:index] do
    member do
      post :like
      post :dislike
    end
  end

  root 'jokes#index'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

end

app/models/joke.rb
class Joke < ActiveRecord::Base

  scope :find_unread_jokes, ->(read_joke_ids) { where.not(id: read_joke_ids) }
end

app/models/jokee.rb
class Joke < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController

  def index
    session[:read_joke_ids] ||= []
    if session[:read_joke_ids].empty?
      @joke = Joke.first
    else
      @joke = Joke.find_unread_jokes(session[:read_joke_ids]).first
    end
  end

  def like
    session[:read_joke_ids] << params[:id]
    joke = Joke.find(params[:id])
    joke.like = joke.like.to_i + 1
    joke.save
    @joke = Joke.find_unread_jokes(session[:read_joke_ids]).first
  end

  def dislike
    session[:read_joke_ids] << params[:id]
    joke = Joke.find(params[:id])
    joke.dislike = joke.dislike.to_i - 1
    joke.save
    @joke = Joke.find_unread_jokes(session[:read_joke_ids]).first
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/jokes/_joke.haml
- if joke
  .container
    .row
      .col-lg-12
        .text-center#content
          = joke.content

        #horizontal-line
          %hr
    .row
      .col-lg-12
        #group-buttons.text-center
          = link_to "This is Funny!", like_joke_path(joke),  class: 'btn btn-success', id: "btn-like", method: 'POST', remote: true
          = link_to "This is not funny.", dislike_joke_path(joke), class: 'btn btn-success', id: 'btn-dislike', method: 'POST', remote: true
- else
  .container
    .row
      .col-lg-12
        .text-center#content That's all the jokes for today! Come back another day!

app/views/jokes/dislike.js.erb
$("#joke-content").html("<%= j(render 'joke', joke: @joke) %>");

app/views/jokes/index.haml
.container
  .navigation
    - if current_user
      %strong= current_user.email
      = link_to "| Log out", destroy_user_session_path, method: :delete
    - else
      = link_to "Sign in", new_user_session_path
#joke-title.text-center
  #title-1 A joke a day keeps the doctor away
  #title-2 If you joke wrong way, your teeth have to pay. (Serious)

#joke-content
  = render "joke", joke: @joke

.container
  #footer.text-center
    #footer-1
      This website is created as part of Testing Ruby on Rails developer program. The materials contained on this website are provided for general 
      information only and do not constitute any form of advice. Testing assumes no responsibility for the accuracy of any particular statement and
      accepts no liability for any loss or damage which may arise from reliance on the information contained on this site. Test changed after deployment.

app/views/jokes/like.js.erb
$("#joke-content").html("<%= j(render 'joke', joke: @joke) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joke</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</body>
</html>